// Bill Management Types

export enum BillType {
  UTILITY = 'utility',
  INSURANCE = 'insurance',
  SUBSCRIPTION = 'subscription',
  SCHOOL_TUITION = 'school_tuition',
  CREDIT_CARD = 'credit_card',
  MEDICAL = 'medical',
  OTHER = 'other',
}

export enum BillStatus {
  PENDING = 'PENDING',
  PAID = 'PAID',
  OVERDUE = 'OVERDUE',
  AUTO_GENERATED = 'AUTO_GENERATED',  // New status for auto-generated bills
}

export enum BillFrequency {
  MONTHLY = 'monthly',
  QUARTERLY = 'quarterly',
  YEARLY = 'yearly',
}

export interface Bill {
  id: string;
  userId: string;
  billName: string;
  billType: BillType;
  amount: number;
  dueDate: string;
  frequency: BillFrequency;
  status: BillStatus;
  createdAt: string;
  updatedAt: string;
  paidAt?: string;
  notes?: string;
  provider?: string;
  referenceNumber?: string;
  autoGenerateNext?: boolean;  // Enable auto-generation for future bills
  isAutoGenerated?: boolean;   // Flag if this bill was auto-generated
  needsConfirmation?: boolean; // Flag if auto-generated bill needs user confirmation
  estimatedAmount?: number;    // Original estimated amount (for auto-generated bills)
}

export interface CreateBillRequest {
  billName: string;
  billType: BillType;
  amount: number;
  dueDate: string;
  frequency: BillFrequency;
  notes?: string;
  provider?: string;
  referenceNumber?: string;
  autoGenerateNext?: boolean;  // Enable auto-generation for this provider
}

export interface UpdateBillRequest {
  billName?: string;
  billType?: BillType;
  amount?: number;
  dueDate?: string;
  frequency?: BillFrequency;
  status?: BillStatus;
  notes?: string;
  provider?: string;
  referenceNumber?: string;
}

export interface BillFilters {
  status?: BillStatus;
  billType?: BillType;
  page?: number;
  limit?: number;
}

export interface BillAnalytics {
  totalPendingAmount: number;
  totalPaidAmount: number;
  totalOverdueAmount: number;
  totalPendingBills: number;
  totalPaidBills: number;
  totalOverdueBills: number;
  generatedAt: string;
}

export interface TotalPaidAnalytics {
  amount: number;
  count: number;
  period: string;
  startDate: string;
  endDate: string;
}

export interface PaginatedBillsResponse {
  data: Bill[];
  page: number;
  limit: number;
  totalCount: number;
  totalPages?: number;
  hasNextPage?: boolean;
  hasPreviousPage?: boolean;
}

export interface ApiResponse<T> {
  success: boolean;
  message: string | null;
  data: T;
  errors: string[];
}

// ==================== VARIABLE MONTHLY BILLING TYPES ====================

// Bill History Analytics
export interface BillHistoryAnalytics {
  bills: Bill[];
  analytics: {
    averageSimple: number;
    averageWeighted: number;
    averageSeasonal?: number;
    totalSpent: number;
    highestBill: number;
    lowestBill: number;
    trend: 'increasing' | 'decreasing' | 'stable';
    monthCount?: number;
    billCount?: number;
    firstBillDate?: string;
    lastBillDate?: string;
  };
  forecast: BillForecast;
  totalCount?: number;
}

// Forecast Data
export interface BillForecast {
  estimatedAmount: number;
  calculationMethod: 'simple' | 'weighted' | 'seasonal';
  confidence: 'low' | 'medium' | 'high';
  estimatedForMonth?: string;
  recommendation?: string;
}

// Variance Analysis
export interface BillVariance {
  billId: string;
  actualAmount: number;
  estimatedAmount: number;
  variance: number;
  variancePercentage: number;
  status: 'over_budget' | 'slightly_over' | 'on_target' | 'under_budget' | 'no_data';
  message: string;
  recommendation: string;
}

// Variance Dashboard
export interface VarianceDashboard {
  totalActualAmount: number;
  totalEstimatedAmount: number;
  totalVariance: number;
  totalBillsAnalyzed: number;
  overBudgetCount: number;
  slightlyOverCount: number;
  onTargetCount: number;
  underBudgetCount: number;
  noDataCount: number;
  variances: BillVariance[];
  generatedAt: string;
}

// Budget Settings
export interface BillBudget {
  id: string;
  userId: string;
  provider: string;
  billType: BillType;
  monthlyBudget: number;
  enableAlerts: boolean;
  alertThreshold: number;
  createdAt: string;
  updatedAt: string;
}

// Create Budget Request
export interface CreateBudgetRequest {
  provider: string;
  billType: BillType;
  monthlyBudget: number;
  enableAlerts: boolean;
  alertThreshold?: number;
}

// Budget Status
export interface BudgetStatus {
  budgetId?: string;
  provider: string;
  billType: BillType;
  monthlyBudget: number;
  currentBill: number;
  remaining: number;
  percentageUsed: number;
  status: 'under_budget' | 'on_track' | 'near_limit' | 'over_budget';
  alert: boolean;
  message: string;
}

// Dashboard Data
export interface BillDashboard {
  currentBills: Bill[];
  upcomingBills: Bill[];
  overdueBills: Bill[];
  providerAnalytics: ProviderAnalytics[];
  budgetStatuses: BudgetStatus[];
  alerts: BillAlert[];
  summary: {
    totalPendingAmount: number;
    totalPaidAmount: number;
    totalOverdueAmount: number;
  };
}

// Provider Analytics
export interface ProviderAnalytics {
  provider: string;
  billType: BillType;
  totalSpent: number;
  averageMonthly: number;
  highestBill: number;
  lowestBill: number;
  billCount: number;
  trend: 'increasing' | 'decreasing' | 'stable';
  monthlySummary: MonthlyBillData[];
}

// Alert Data
export interface BillAlert {
  id: string;
  type: 'budget_exceeded' | 'trend_increase' | 'unusual_spike' | 'due_reminder' | 'overdue' | 'savings';
  severity: 'info' | 'warning' | 'error' | 'success';
  title: string;
  message: string;
  billId?: string;
  provider?: string;
  amount?: number;
  createdAt: string;
  read: boolean;
}

// Monthly Trend Point
export interface MonthlyBillData {
  month: string;
  year: number;
  amount: number;
  status: BillStatus;
  dueDate: string;
  paidDate?: string;
  billId?: string;
}