// Utility Management Types

export enum UtilityType {
  ELECTRICITY = 'ELECTRICITY',
  WATER = 'WATER',
  GAS = 'GAS',
  INTERNET = 'INTERNET',
  PHONE = 'PHONE',
  SEWER = 'SEWER',
  TRASH = 'TRASH',
}

export enum UtilityStatus {
  PENDING = 'PENDING',
  PAID = 'PAID',
  OVERDUE = 'OVERDUE',
}

export interface Utility {
  id: string;
  userId: string;
  utilityName: string;
  utilityType: UtilityType | string;
  provider: string;
  accountNumber?: string;
  unit?: string; // kWh, gallons, therms, MB, etc.
  consumption?: number; // Units consumed
  costPerUnit?: number; // Cost per unit
  amount: number;
  billingDate: string;
  dueDate: string;
  status: UtilityStatus | string;
  notes?: string;
  referenceNumber?: string;
  previousReading?: number;
  currentReading?: number;
  readingDate?: string;
  propertyAddress?: string;
  meterNumber?: string;
  autoGenerateNext?: boolean;
  isAutoGenerated?: boolean;
  confirmedAt?: string;
  parentUtilityId?: string;
  createdAt: string;
  updatedAt: string;
  paidAt?: string;
}

export interface CreateUtilityRequest {
  utilityName: string;
  utilityType: UtilityType | string;
  provider: string;
  accountNumber?: string;
  unit?: string;
  consumption?: number;
  costPerUnit?: number;
  amount: number;
  billingDate: string;
  dueDate: string;
  notes?: string;
  referenceNumber?: string;
  previousReading?: number;
  currentReading?: number;
  readingDate?: string;
  propertyAddress?: string;
  meterNumber?: string;
  autoGenerateNext?: boolean;
}

export interface UpdateUtilityRequest {
  utilityName?: string;
  utilityType?: UtilityType | string;
  provider?: string;
  accountNumber?: string;
  unit?: string;
  consumption?: number;
  costPerUnit?: number;
  amount?: number;
  billingDate?: string;
  dueDate?: string;
  notes?: string;
  referenceNumber?: string;
  previousReading?: number;
  currentReading?: number;
  readingDate?: string;
  propertyAddress?: string;
  meterNumber?: string;
  autoGenerateNext?: boolean;
}

export interface UtilityFilters {
  status?: string;
  utilityType?: string;
  page?: number;
  limit?: number;
}

export interface UtilityAnalytics {
  totalPendingAmount: number;
  totalPaidAmount: number;
  totalOverdueAmount: number;
  totalUtilities: number;
  pendingCount: number;
  paidCount: number;
  overdueCount: number;
  byType: UtilityTypeSummary[];
  byProvider: ProviderSummary[];
}

export interface UtilityTypeSummary {
  utilityType: string;
  totalAmount: number;
  totalConsumption?: number;
  averageCostPerUnit?: number;
  count: number;
}

export interface ProviderSummary {
  provider: string;
  utilityType: string;
  totalAmount: number;
  totalConsumption?: number;
  averageCostPerUnit?: number;
  count: number;
}

export interface UtilityConsumptionHistory {
  utilityId: string;
  utilityName: string;
  utilityType: string;
  provider: string;
  history: ConsumptionDataPoint[];
  averageConsumption?: number;
  averageCost: number;
  averageCostPerUnit?: number;
  trendPercentage?: number; // Positive = increasing, Negative = decreasing
}

export interface ConsumptionDataPoint {
  billingDate: string;
  consumption?: number;
  amount: number;
  costPerUnit?: number;
  previousReading?: number;
  currentReading?: number;
  status: string;
}

export interface UtilityComparison {
  utilityType: string;
  providers: ProviderComparison[];
  averageCost: number;
  averageConsumption?: number;
  averageCostPerUnit?: number;
  recommendedProvider?: string;
  potentialSavings?: number;
}

export interface ProviderComparison {
  provider: string;
  averageAmount: number;
  averageConsumption?: number;
  averageCostPerUnit?: number;
  billCount: number;
  lastBillDate?: string;
  totalSpent: number;
}

export interface MarkUtilityPaidRequest {
  notes?: string;
  bankAccountId?: string;
}

