import React, { useState, useEffect } from 'react';
import {
  Box,
  Typography,
  Grid,
  Card,
  CardContent,
  Button,
  Alert,
  Fab,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  Chip,
  IconButton,
  Tooltip,
  ToggleButtonGroup,
  ToggleButton,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Paper,
  Skeleton,
} from '@mui/material';
import {
  Add as AddIcon,
  Receipt,
  TrendingUp,
  Warning,
  CheckCircle,
  FilterList,
  Refresh,
  ViewModule,
  ViewList,
  Edit,
  Delete,
  CheckCircle as CheckCircleIcon,
} from '@mui/icons-material';
import { useAuth } from '../contexts/AuthContext';
import { useCurrency } from '../contexts/CurrencyContext';
import { useNavigate } from 'react-router-dom';
import { apiService } from '../services/api';
import { 
  Bill, 
  BillStatus, 
  BillType, 
  BillFilters, 
  BillAnalytics, 
  ProviderAnalytics, 
  BillAlert 
} from '../types/bill';
import { getErrorMessage } from '../utils/validation';
import BillCard from '../components/Bills/BillCard';
import BillForm from '../components/Bills/BillForm';

const Bills: React.FC = () => {
  const { user } = useAuth();
  const { formatCurrency } = useCurrency();
  const navigate = useNavigate();
  const [bills, setBills] = useState<Bill[]>([]);
  const [analytics, setAnalytics] = useState<BillAnalytics | null>(null);
  const [providerAnalytics, setProviderAnalytics] = useState<ProviderAnalytics[]>([]);
  const [alerts, setAlerts] = useState<BillAlert[]>([]);
  const [autoGeneratedBills, setAutoGeneratedBills] = useState<Bill[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string>('');
  const [successMessage, setSuccessMessage] = useState<string>('');
  const [showBillForm, setShowBillForm] = useState(false);
  const [selectedBill, setSelectedBill] = useState<Bill | null>(null);
  const [isEditingSpecificMonth, setIsEditingSpecificMonth] = useState(false);
  const [filters, setFilters] = useState<BillFilters>({
    page: 1,
    limit: 10000,
  });
  const [showFilters, setShowFilters] = useState(false);
  const [viewMode, setViewMode] = useState<'card' | 'table'>('card');

  // Group bills by billName to show the earliest unpaid bill per group
  const groupedBills = React.useMemo(() => {
    return bills.reduce((acc, bill) => {
      // Extract base name by removing date suffixes like " - Apr 2026", " - Jan 2026", etc.
      const baseName = bill.billName?.replace(/\s*-\s*(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s*\d{4}$/i, '').trim();
      const key = baseName || bill.billName || `${bill.provider}-${bill.billType}`;
      
      if (!acc[key]) {
        acc[key] = {
          latestBill: bill,
          allBills: [bill],
          count: 1,
          baseName: baseName || bill.billName || `${bill.provider} ${bill.billType}`
        };
      } else {
        acc[key].allBills.push(bill);
        acc[key].count++;
        
        // Prioritize earliest unpaid (PENDING) bill, otherwise latest bill overall
        const currentIsUnpaid = acc[key].latestBill.status === BillStatus.PENDING;
        const newIsUnpaid = bill.status === BillStatus.PENDING;
        const currentDate = new Date(acc[key].latestBill.dueDate);
        const newDate = new Date(bill.dueDate);
        
        // Replace if: new bill is unpaid and (current is paid OR new is earlier/older)
        if (newIsUnpaid && (!currentIsUnpaid || newDate < currentDate)) {
          acc[key].latestBill = bill;
        } else if (!newIsUnpaid && !currentIsUnpaid && newDate > currentDate) {
          // Both are paid, keep the most recent
          acc[key].latestBill = bill;
        }
      }
      
      return acc;
    }, {} as Record<string, { latestBill: Bill; allBills: Bill[]; count: number; baseName: string }>);
  }, [bills]);

  // Get array of latest bills only for display
  const displayBills = React.useMemo(() => {
    const result = Object.values(groupedBills).map(group => group.latestBill);
    
    // Debug logging
    console.log('📊 Bill Grouping Summary:');
    console.log('Total bills from API:', bills.length);
    console.log('Total groups (cards to display):', result.length);
    console.log('Grouped bills detail:', Object.entries(groupedBills).map(([key, group]) => ({
      groupName: key,
      baseName: group.baseName,
      count: group.count,
      bills: group.allBills.map(b => ({
        id: b.id,
        fullName: b.billName,
        dueDate: b.dueDate,
        status: b.status
      }))
    })));
    
    return result;
  }, [groupedBills, bills.length]);

  // Calculate current month analytics
  const currentMonthAnalytics = React.useMemo(() => {
    const now = new Date();
    const currentMonth = now.getMonth();
    const currentYear = now.getFullYear();
    
    // Filter bills for current month
    const currentMonthBills = bills.filter(bill => {
      const billDate = new Date(bill.dueDate);
      return billDate.getMonth() === currentMonth && billDate.getFullYear() === currentYear;
    });
    
    // Calculate analytics for current month
    const totalBills = currentMonthBills.length;
    const pendingBills = currentMonthBills.filter(b => b.status === BillStatus.PENDING);
    const paidBills = currentMonthBills.filter(b => b.status === BillStatus.PAID);
    const overdueBills = currentMonthBills.filter(b => 
      b.status === BillStatus.PENDING && new Date(b.dueDate) < now
    );
    
    const totalPendingAmount = pendingBills.reduce((sum, b) => sum + b.amount, 0);
    const totalPaidAmount = paidBills.reduce((sum, b) => sum + b.amount, 0);
    const totalOverdueAmount = overdueBills.reduce((sum, b) => sum + b.amount, 0);
    
    return {
      totalBills,
      totalPendingBills: pendingBills.length,
      totalPaidBills: paidBills.length,
      totalOverdueBills: overdueBills.length,
      totalPendingAmount,
      totalPaidAmount,
      totalOverdueAmount,
    };
  }, [bills]);

  useEffect(() => {
    if (user) {
      loadAllData();
    }
  }, [user, filters]);

  const loadAllData = async () => {
    await Promise.all([
      loadBills(),
      loadAnalytics(),
      loadProviderAnalytics(),
      loadAlerts(),
      loadAutoGeneratedBills(),
    ]);
  };

  const loadAutoGeneratedBills = async () => {
    try {
      const data = await apiService.getAutoGeneratedBills(false); // Get unconfirmed bills
      setAutoGeneratedBills(data || []);
    } catch (err: unknown) {
      console.error('Failed to load auto-generated bills:', err);
      setAutoGeneratedBills([]);
    }
  };

  const loadBills = async () => {
    try {
      setIsLoading(true);
      console.log('=== Bills Page: Loading bills ===');
      console.log('Current user:', user?.email, 'User ID:', user?.id);
      console.log('Filters:', filters);
      const response = await apiService.getUserBills(filters);
      console.log('Bills response:', response);
      console.log('Number of bills:', response.data?.length);
      if (response.data?.length > 0) {
        console.log('First bill sample:', response.data[0]);
        console.log('Bill userId:', response.data[0].userId);
        console.log('Does bill userId match current user?', response.data[0].userId === user?.id);
      }
      console.log('=========================');
      
      // Ensure we always set an array, even if response.data is null/undefined
      const billsData = response.data || [];
      setBills(billsData);
    } catch (err: unknown) {
      console.error('Error loading bills:', err);
      setError(getErrorMessage(err, 'Failed to load bills'));
      // Set empty array on error to prevent white screen
      setBills([]);
    } finally {
      setIsLoading(false);
    }
  };

  const loadAnalytics = async () => {
    try {
      const analyticsData = await apiService.getBillAnalyticsSummary();
      setAnalytics(analyticsData || null);
    } catch (err: unknown) {
      console.error('Failed to load analytics:', err);
      setAnalytics(null);
    }
  };

  const loadProviderAnalytics = async () => {
    try {
      const data = await apiService.getProviderAnalytics();
      setProviderAnalytics(data || []);
    } catch (err: unknown) {
      console.error('Failed to load provider analytics:', err);
      setProviderAnalytics([]);
    }
  };

  const loadAlerts = async () => {
    try {
      const data = await apiService.getBillAlerts();
      setAlerts(data || []);
    } catch (err: unknown) {
      console.error('Failed to load alerts:', err);
      setAlerts([]);
    }
  };

  const handleViewProviderDetails = (provider: string, billType: BillType) => {
    navigate(`/bills/${encodeURIComponent(provider)}/${billType}`);
  };

  const handleCreateBill = () => {
    setSelectedBill(null);
    setShowBillForm(true);
  };

  const handleEditBill = (bill: Bill, isSpecificMonth: boolean = false) => {
    setSelectedBill(bill);
    setIsEditingSpecificMonth(isSpecificMonth);
    setShowBillForm(true);
  };

  const handleBillSuccess = (bill: Bill) => {
    setShowBillForm(false);
    setSelectedBill(null);
    loadBills();
    loadAnalytics();
  };

  const handleDeleteBill = async (billId: string) => {
    if (window.confirm('Are you sure you want to delete this bill? This action cannot be undone.')) {
      try {
        console.log('Deleting bill with ID:', billId);
        setError('');
        setSuccessMessage('');
        const response = await apiService.deleteBill(billId);
        console.log('Delete response:', response);
        
        if (response.success) {
          setSuccessMessage(response.message);
          // Auto-hide success message after 5 seconds
          setTimeout(() => setSuccessMessage(''), 5000);
          console.log('Reloading data after successful delete...');
          await loadAllData();
        } else {
          setError('Failed to delete bill');
        }
      } catch (err: unknown) {
        console.error('Delete error:', err);
        const errorMessage = getErrorMessage(err, 'Failed to delete bill');
        setError(errorMessage);
        
        // Don't reload if bill not found (404)
        if (!errorMessage.includes('not found')) {
          await loadBills();
        }
      }
    }
  };

  const handleMarkAsPaid = async (billId: string) => {
    try {
      await apiService.markBillAsPaid(billId, 'Marked as paid from dashboard');
      loadBills();
      loadAnalytics();
    } catch (err: unknown) {
      setError(getErrorMessage(err, 'Failed to mark bill as paid'));
    }
  };

  const handleFilterChange = (field: keyof BillFilters, value: any) => {
    setFilters(prev => ({
      ...prev,
      [field]: value,
      page: 1, // Reset to first page when filters change
    }));
  };

  const clearFilters = () => {
    setFilters({
      page: 1,
      limit: 12,
    });
  };

  const refreshData = () => {
    loadBills();
    loadAnalytics();
  };

  if (isLoading) {
    return (
      <Box sx={{ p: { xs: 2, sm: 3 } }}>
        {/* Header Skeleton */}
        <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 3 }}>
          <Skeleton variant="text" width={300} height={40} />
          <Box sx={{ display: 'flex', gap: 1 }}>
            <Skeleton variant="rectangular" width={40} height={40} sx={{ borderRadius: 1 }} />
            <Skeleton variant="rectangular" width={40} height={40} sx={{ borderRadius: 1 }} />
            <Skeleton variant="rectangular" width={80} height={40} sx={{ borderRadius: 1 }} />
            <Skeleton variant="rectangular" width={100} height={40} sx={{ borderRadius: 1 }} />
          </Box>
        </Box>

        {/* Analytics Cards Skeleton */}
        <Grid container spacing={3} sx={{ mb: 4 }}>
          {[1, 2, 3, 4].map((i) => (
            <Grid item xs={12} sm={6} md={3} key={i}>
              <Card>
                <CardContent>
                  <Box sx={{ display: 'flex', alignItems: 'center' }}>
                    <Skeleton variant="circular" width={40} height={40} sx={{ mr: 2 }} />
                    <Box sx={{ flex: 1 }}>
                      <Skeleton variant="text" width="60%" height={30} />
                      <Skeleton variant="text" width="80%" height={20} />
                    </Box>
                  </Box>
                </CardContent>
              </Card>
            </Grid>
          ))}
        </Grid>

        {/* Bill Cards Skeleton */}
        <Grid container spacing={3}>
          {[1, 2, 3, 4, 5, 6].map((i) => (
            <Grid item xs={12} sm={6} md={4} key={i}>
              <Card>
                <CardContent>
                  <Skeleton variant="text" width="70%" height={28} sx={{ mb: 1 }} />
                  <Skeleton variant="text" width="50%" height={24} sx={{ mb: 2 }} />
                  <Skeleton variant="rectangular" width="100%" height={60} sx={{ mb: 1, borderRadius: 1 }} />
                  <Box sx={{ display: 'flex', justifyContent: 'space-between', mt: 2 }}>
                    <Skeleton variant="rectangular" width={80} height={36} sx={{ borderRadius: 1 }} />
                    <Skeleton variant="rectangular" width={80} height={36} sx={{ borderRadius: 1 }} />
                  </Box>
                </CardContent>
              </Card>
            </Grid>
          ))}
        </Grid>
      </Box>
    );
  }

  return (
    <Box sx={{ p: { xs: 2, sm: 3 } }}>
      <Box sx={{ 
        display: 'flex', 
        flexDirection: { xs: 'column', sm: 'row' },
        justifyContent: 'space-between', 
        alignItems: { xs: 'flex-start', sm: 'center' }, 
        mb: 3,
        gap: 2
      }}>
        <Typography variant="h4" component="h1" sx={{ fontSize: { xs: '1.75rem', sm: '2.125rem' } }}>
          Bills and Utility Management
        </Typography>
        <Box sx={{ display: 'flex', gap: 1, flexWrap: 'wrap', width: { xs: '100%', sm: 'auto' }, alignItems: 'center' }}>
          <ToggleButtonGroup
            value={viewMode}
            exclusive
            onChange={(e, newView) => newView && setViewMode(newView)}
            size="small"
            aria-label="view mode"
          >
            <ToggleButton value="card" aria-label="card view">
              <Tooltip title="Card View">
                <ViewModule />
              </Tooltip>
            </ToggleButton>
            <ToggleButton value="table" aria-label="table view">
              <Tooltip title="Table View">
                <ViewList />
              </Tooltip>
            </ToggleButton>
          </ToggleButtonGroup>
          <Tooltip title="Refresh">
            <IconButton onClick={refreshData} disabled={isLoading}>
              <Refresh />
            </IconButton>
          </Tooltip>
          <Button
            variant="outlined"
            startIcon={<FilterList />}
            onClick={() => setShowFilters(!showFilters)}
            size="small"
            sx={{ flex: { xs: 1, sm: 'none' } }}
          >
            Filters
          </Button>
          <Button
            variant="contained"
            startIcon={<AddIcon />}
            onClick={handleCreateBill}
            size="small"
            sx={{ flex: { xs: 1, flex: 'none' }, display: { xs: 'none', sm: 'inline-flex' } }}
          >
            Add Bill
          </Button>
        </Box>
      </Box>

      {error && (
        <Alert severity="error" sx={{ mb: 3 }} onClose={() => setError('')}>
          {error}
        </Alert>
      )}

      {successMessage && (
        <Alert severity="success" sx={{ mb: 3 }} onClose={() => setSuccessMessage('')}>
          {successMessage}
        </Alert>
      )}


      {/* Analytics Cards - Current Month Only */}
      <Grid container spacing={3} sx={{ mb: 4 }}>
        <Grid item xs={12} sm={6} md={3}>
          <Card>
            <CardContent>
              <Box sx={{ display: 'flex', alignItems: 'center' }}>
                <Receipt sx={{ mr: 2, color: 'warning.main' }} />
                <Box>
                  <Typography variant="h6">
                    {formatCurrency(currentMonthAnalytics.totalPendingAmount)}
                  </Typography>
                  <Typography variant="body2" color="text.secondary">
                    Pending This Month ({currentMonthAnalytics.totalPendingBills})
                  </Typography>
                </Box>
              </Box>
            </CardContent>
          </Card>
        </Grid>

        <Grid item xs={12} sm={6} md={3}>
          <Card>
            <CardContent>
              <Box sx={{ display: 'flex', alignItems: 'center' }}>
                <CheckCircle sx={{ mr: 2, color: 'success.main' }} />
                <Box>
                  <Typography variant="h6">
                    {formatCurrency(currentMonthAnalytics.totalPaidAmount)}
                  </Typography>
                  <Typography variant="body2" color="text.secondary">
                    Paid This Month ({currentMonthAnalytics.totalPaidBills})
                  </Typography>
                </Box>
              </Box>
            </CardContent>
          </Card>
        </Grid>

        <Grid item xs={12} sm={6} md={3}>
          <Card>
            <CardContent>
              <Box sx={{ display: 'flex', alignItems: 'center' }}>
                <Warning sx={{ mr: 2, color: 'error.main' }} />
                <Box>
                  <Typography variant="h6">
                    {formatCurrency(currentMonthAnalytics.totalOverdueAmount)}
                  </Typography>
                  <Typography variant="body2" color="text.secondary">
                    Overdue This Month ({currentMonthAnalytics.totalOverdueBills})
                  </Typography>
                </Box>
              </Box>
            </CardContent>
          </Card>
        </Grid>

        <Grid item xs={12} sm={6} md={3}>
          <Card>
            <CardContent>
              <Box sx={{ display: 'flex', alignItems: 'center' }}>
                <TrendingUp sx={{ mr: 2, color: 'primary.main' }} />
                <Box>
                  <Typography variant="h6">
                    {currentMonthAnalytics.totalBills}
                  </Typography>
                  <Typography variant="body2" color="text.secondary">
                    Total Bills This Month
                  </Typography>
                </Box>
              </Box>
            </CardContent>
          </Card>
        </Grid>
      </Grid>

      {/* Main Content Layout */}
      <Grid container spacing={3}>
        {/* Bills Content - Full Width */}
        <Grid item xs={12}>
          {/* Filters */}
      {showFilters && (
        <Card sx={{ mb: 3 }}>
          <CardContent>
            <Typography variant="h6" gutterBottom>
              Filters
            </Typography>
            <Grid container spacing={2} alignItems="center">
              <Grid item xs={12} sm={4}>
                <FormControl fullWidth>
                  <InputLabel>Status</InputLabel>
                  <Select
                    value={filters.status || ''}
                    onChange={(e) => handleFilterChange('status', e.target.value || undefined)}
                    label="Status"
                  >
                    <MenuItem value="">All Statuses</MenuItem>
                    <MenuItem value={BillStatus.PENDING}>Pending</MenuItem>
                    <MenuItem value={BillStatus.PAID}>Paid</MenuItem>
                    <MenuItem value={BillStatus.OVERDUE}>Overdue</MenuItem>
                  </Select>
                </FormControl>
              </Grid>

              <Grid item xs={12} sm={4}>
                <FormControl fullWidth>
                  <InputLabel>Bill Type</InputLabel>
                  <Select
                    value={filters.billType || ''}
                    onChange={(e) => handleFilterChange('billType', e.target.value || undefined)}
                    label="Bill Type"
                  >
                    <MenuItem value="">All Types</MenuItem>
                    <MenuItem value={BillType.UTILITY}>Utility (Water, Electricity, Gas)</MenuItem>
                    <MenuItem value={BillType.INSURANCE}>Insurance (Health, Car, Life)</MenuItem>
                    <MenuItem value={BillType.SUBSCRIPTION}>Subscriptions (Netflix, Spotify, Adobe)</MenuItem>
                    <MenuItem value={BillType.SCHOOL_TUITION}>School Tuition</MenuItem>
                    <MenuItem value={BillType.CREDIT_CARD}>Credit Card Bill</MenuItem>
                    <MenuItem value={BillType.MEDICAL}>Medical Bill</MenuItem>
                    <MenuItem value={BillType.OTHER}>Other</MenuItem>
                  </Select>
                </FormControl>
              </Grid>

              <Grid item xs={12} sm={4}>
                <Box sx={{ display: 'flex', gap: 1 }}>
                  <Button variant="outlined" onClick={clearFilters}>
                    Clear
                  </Button>
                </Box>
              </Grid>
            </Grid>

            {/* Active Filters */}
            {(filters.status || filters.billType) && (
              <Box sx={{ mt: 2 }}>
                <Typography variant="body2" color="text.secondary" gutterBottom>
                  Active Filters:
                </Typography>
                <Box sx={{ display: 'flex', gap: 1, flexWrap: 'wrap' }}>
                  {filters.status && (
                    <Chip
                      label={`Status: ${filters.status}`}
                      onDelete={() => handleFilterChange('status', undefined)}
                      size="small"
                    />
                  )}
                  {filters.billType && (
                    <Chip
                      label={`Type: ${filters.billType}`}
                      onDelete={() => handleFilterChange('billType', undefined)}
                      size="small"
                    />
                  )}
                </Box>
              </Box>
            )}
          </CardContent>
        </Card>
      )}

          {/* Bills Grid/Table */}
          {displayBills.length === 0 ? (
            <Card>
              <CardContent sx={{ textAlign: 'center', py: 6 }}>
                <Receipt sx={{ fontSize: 64, color: 'text.secondary', mb: 2 }} />
                <Typography variant="h6" gutterBottom>
                  No bills found
                </Typography>
                <Typography variant="body2" color="text.secondary" sx={{ mb: 3 }}>
                  {filters.status || filters.billType 
                    ? 'No bills match your current filters. Try adjusting your filters or create a new bill.'
                    : 'You haven\'t created any bills yet. Start by adding your first bill.'
                  }
                </Typography>
                <Button
                  variant="contained"
                  startIcon={<AddIcon />}
                  onClick={handleCreateBill}
                >
                  Add Bill
                </Button>
              </CardContent>
            </Card>
          ) : viewMode === 'card' ? (
            <Grid container spacing={3}>
              {displayBills.map((bill) => {
                // Extract base name from bill
                const baseName = bill.billName?.replace(/\s*-\s*(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s*\d{4}$/i, '').trim();
                const groupKey = baseName || bill.billName || `${bill.provider}-${bill.billType}`;
                const billGroup = groupedBills[groupKey];
                
                // Create a display bill with the base name
                const displayBill = {
                  ...bill,
                  billName: billGroup?.baseName || bill.billName
                };
                
                return (
                  <Grid item xs={12} sm={6} md={4} key={bill.id}>
                    <BillCard
                      bill={displayBill}
                      alerts={alerts}
                      historicalCount={billGroup.count - 1}
                      allBills={billGroup.allBills}
                      onEdit={handleEditBill}
                      onDelete={handleDeleteBill}
                      onMarkAsPaid={handleMarkAsPaid}
                      onViewHistory={handleViewProviderDetails}
                      onBillConfirmed={loadAllData}
                    />
                  </Grid>
                );
              })}
            </Grid>
          ) : (
            <TableContainer component={Paper}>
              <Table>
                <TableHead>
                  <TableRow>
                    <TableCell>Bill Name</TableCell>
                    <TableCell>Provider</TableCell>
                    <TableCell>Type</TableCell>
                    <TableCell align="right">Amount</TableCell>
                    <TableCell>Due Date</TableCell>
                    <TableCell>Status</TableCell>
                    <TableCell align="center">Actions</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {displayBills.map((bill) => {
                    // Extract base name from bill
                    const baseName = bill.billName?.replace(/\s*-\s*(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s*\d{4}$/i, '').trim();
                    const groupKey = baseName || bill.billName || `${bill.provider}-${bill.billType}`;
                    const billGroup = groupedBills[groupKey];
                    
                    const displayBill = {
                      ...bill,
                      billName: billGroup?.baseName || bill.billName
                    };
                    
                    const isOverdue = new Date(bill.dueDate) < new Date() && bill.status === BillStatus.PENDING;
                    
                    return (
                      <TableRow key={bill.id} hover>
                        <TableCell>
                          <Typography variant="body2" fontWeight="medium">
                            {displayBill.billName}
                          </Typography>
                          {billGroup.count > 1 && (
                            <Typography variant="caption" color="text.secondary">
                              ({billGroup.count} periods)
                            </Typography>
                          )}
                        </TableCell>
                        <TableCell>
                          <Typography variant="body2">
                            {bill.provider || 'N/A'}
                          </Typography>
                        </TableCell>
                        <TableCell>
                          <Chip
                            label={bill.billType}
                            size="small"
                            sx={{ fontSize: '0.75rem' }}
                          />
                        </TableCell>
                        <TableCell align="right">
                          <Typography 
                            variant="body2" 
                            fontWeight="bold"
                            color={isOverdue ? 'error.main' : 'text.primary'}
                          >
                            {formatCurrency(bill.amount)}
                          </Typography>
                        </TableCell>
                        <TableCell>
                          <Typography 
                            variant="body2"
                            color={isOverdue ? 'error.main' : 'text.primary'}
                          >
                            {new Date(bill.dueDate).toLocaleDateString()}
                          </Typography>
                        </TableCell>
                        <TableCell>
                          <Chip
                            label={bill.status}
                            color={
                              bill.status === BillStatus.PAID ? 'success' :
                              bill.status === BillStatus.OVERDUE ? 'error' :
                              'warning'
                            }
                            size="small"
                          />
                        </TableCell>
                        <TableCell align="center">
                          <Box sx={{ display: 'flex', gap: 0.5, justifyContent: 'center' }}>
                            <Tooltip title="Edit">
                              <IconButton
                                size="small"
                                onClick={() => handleEditBill(bill)}
                              >
                                <Edit fontSize="small" />
                              </IconButton>
                            </Tooltip>
                            {bill.status === BillStatus.PENDING && (
                              <Tooltip title="Mark as Paid">
                                <IconButton
                                  size="small"
                                  color="success"
                                  onClick={() => handleMarkAsPaid(bill.id)}
                                >
                                  <CheckCircleIcon fontSize="small" />
                                </IconButton>
                              </Tooltip>
                            )}
                            <Tooltip title="Delete">
                              <IconButton
                                size="small"
                                color="error"
                                onClick={() => handleDeleteBill(bill.id)}
                              >
                                <Delete fontSize="small" />
                              </IconButton>
                            </Tooltip>
                          </Box>
                        </TableCell>
                      </TableRow>
                    );
                  })}
                </TableBody>
              </Table>
            </TableContainer>
          )}
        </Grid>
      </Grid>

      {/* Floating Action Button for Mobile */}
      <Fab
        color="primary"
        aria-label="add bill"
        sx={{
          position: 'fixed',
          bottom: 16,
          right: 16,
          display: { xs: 'flex', sm: 'none' },
        }}
        onClick={handleCreateBill}
      >
        <AddIcon />
      </Fab>

      {/* Bill Form Dialog */}
      <BillForm
        open={showBillForm}
        onClose={() => {
          setShowBillForm(false);
          setSelectedBill(null);
          setIsEditingSpecificMonth(false);
        }}
        bill={selectedBill}
        onSuccess={handleBillSuccess}
        lockedFields={isEditingSpecificMonth}
      />
    </Box>
  );
};

export default Bills;