import React, { useState } from 'react';
import {
  Card,
  CardContent,
  Typography,
  Box,
  List,
  ListItem,
  ListItemText,
  Button,
  Chip,
  Alert,
  Divider,
  IconButton,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField,
  CircularProgress,
} from '@mui/material';
import {
  CheckCircle,
  Edit,
  AutoAwesome,
  Info,
} from '@mui/icons-material';
import { Bill, BillStatus } from '../../types/bill';
import { apiService } from '../../services/api';
import { getErrorMessage } from '../../utils/validation';

interface AutoGeneratedBillsListProps {
  bills: Bill[];
  onBillConfirmed?: () => void;
}

const AutoGeneratedBillsList: React.FC<AutoGeneratedBillsListProps> = ({
  bills,
  onBillConfirmed,
}) => {
  const [selectedBill, setSelectedBill] = useState<Bill | null>(null);
  const [showUpdateDialog, setShowUpdateDialog] = useState(false);
  const [updateAmount, setUpdateAmount] = useState(0);
  const [updateNotes, setUpdateNotes] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-US', {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    }).format(amount);
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      month: 'long',
      day: 'numeric',
      year: 'numeric',
    });
  };

  const handleQuickConfirm = async (bill: Bill) => {
    try {
      setLoading(true);
      setError('');
      await apiService.confirmBillAmount(bill.id, bill.amount);
      onBillConfirmed?.();
    } catch (err: unknown) {
      setError(getErrorMessage(err, 'Failed to confirm bill'));
    } finally {
      setLoading(false);
    }
  };

  const handleOpenUpdateDialog = (bill: Bill) => {
    setSelectedBill(bill);
    setUpdateAmount(bill.amount);
    setUpdateNotes('');
    setShowUpdateDialog(true);
  };

  const handleUpdateAmount = async () => {
    if (!selectedBill) return;

    try {
      setLoading(true);
      setError('');
      
      if (updateAmount <= 0) {
        setError('Amount must be greater than 0');
        return;
      }

      await apiService.confirmBillAmount(selectedBill.id, updateAmount, updateNotes);
      setShowUpdateDialog(false);
      setSelectedBill(null);
      onBillConfirmed?.();
    } catch (err: unknown) {
      setError(getErrorMessage(err, 'Failed to update bill amount'));
    } finally {
      setLoading(false);
    }
  };

  if (bills.length === 0) {
    return (
      <Card>
        <CardContent>
          <Box sx={{ textAlign: 'center', py: 3 }}>
            <AutoAwesome sx={{ fontSize: 48, color: 'text.secondary', mb: 2 }} />
            <Typography variant="h6" color="text.secondary">
              No Auto-Generated Bills
            </Typography>
            <Typography variant="body2" color="text.secondary">
              Enable auto-generation when creating bills to save time!
            </Typography>
          </Box>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card>
      <CardContent>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 2 }}>
          <AutoAwesome color="primary" />
          <Typography variant="h6">Auto-Generated Bills</Typography>
          <Chip
            label={`${bills.length} pending confirmation`}
            color="warning"
            size="small"
          />
        </Box>

        <Alert severity="info" sx={{ mb: 2 }} icon={<Info />}>
          These bills were automatically generated based on your historical data. Confirm or update the amounts when your actual bills arrive.
        </Alert>

        {error && (
          <Alert severity="error" sx={{ mb: 2 }} onClose={() => setError('')}>
            {error}
          </Alert>
        )}

        <List disablePadding>
          {bills.map((bill, index) => (
            <React.Fragment key={bill.id}>
              <ListItem
                sx={{
                  border: 1,
                  borderColor: 'primary.light',
                  borderRadius: 1,
                  mb: 1,
                  bgcolor: 'action.hover',
                  flexDirection: 'column',
                  alignItems: 'stretch',
                }}
              >
                <Box sx={{ width: '100%', mb: 1 }}>
                  <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', mb: 1 }}>
                    <Box>
                      <Typography variant="subtitle1" fontWeight="medium">
                        {bill.billName}
                      </Typography>
                      <Typography variant="caption" color="text.secondary">
                        {bill.provider} • Due: {formatDate(bill.dueDate)}
                      </Typography>
                    </Box>
                    <Chip
                      label="Auto-Generated"
                      color="primary"
                      size="small"
                      icon={<AutoAwesome />}
                    />
                  </Box>

                  <Box sx={{ mb: 2 }}>
                    <Typography variant="body2" color="text.secondary" gutterBottom>
                      Estimated Amount:
                    </Typography>
                    <Typography variant="h5" color="primary.main" fontWeight="bold">
                      {formatCurrency(bill.amount)}
                    </Typography>
                    {bill.estimatedAmount && bill.estimatedAmount !== bill.amount && (
                      <Typography variant="caption" color="text.secondary">
                        Original estimate: {formatCurrency(bill.estimatedAmount)}
                      </Typography>
                    )}
                  </Box>

                  <Box sx={{ display: 'flex', gap: 1, flexWrap: 'wrap' }}>
                    <Button
                      variant="contained"
                      size="small"
                      startIcon={<CheckCircle />}
                      onClick={() => handleQuickConfirm(bill)}
                      disabled={loading}
                      color="success"
                    >
                      ✓ Confirm Amount
                    </Button>
                    <Button
                      variant="outlined"
                      size="small"
                      startIcon={<Edit />}
                      onClick={() => handleOpenUpdateDialog(bill)}
                      disabled={loading}
                    >
                      Update Amount
                    </Button>
                  </Box>
                </Box>
              </ListItem>
              {index < bills.length - 1 && <Divider sx={{ my: 1 }} />}
            </React.Fragment>
          ))}
        </List>
      </CardContent>

      {/* Update Amount Dialog */}
      <Dialog open={showUpdateDialog} onClose={() => setShowUpdateDialog(false)} maxWidth="sm" fullWidth>
        <DialogTitle>Update Bill Amount</DialogTitle>
        <DialogContent>
          {selectedBill && (
            <Box sx={{ mt: 2 }}>
              <Typography variant="body2" color="text.secondary" gutterBottom>
                {selectedBill.billName}
              </Typography>
              <Typography variant="caption" color="text.secondary" display="block" sx={{ mb: 3 }}>
                Estimated: {formatCurrency(selectedBill.amount)}
              </Typography>

              {error && (
                <Alert severity="error" sx={{ mb: 2 }} onClose={() => setError('')}>
                  {error}
                </Alert>
              )}

              <TextField
                fullWidth
                label="Actual Amount"
                type="number"
                value={updateAmount}
                onChange={(e) => setUpdateAmount(parseFloat(e.target.value) || 0)}
                InputProps={{
                  startAdornment: '$',
                }}
                inputProps={{ min: 0, step: 0.01 }}
                helperText="Enter the actual amount from your bill"
                sx={{ mb: 2 }}
              />

              <TextField
                fullWidth
                label="Notes (Optional)"
                value={updateNotes}
                onChange={(e) => setUpdateNotes(e.target.value)}
                multiline
                rows={2}
                helperText="Why was it different from the estimate?"
                placeholder="e.g., Higher AC usage this month"
              />
            </Box>
          )}
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setShowUpdateDialog(false)} disabled={loading}>
            Cancel
          </Button>
          <Button
            onClick={handleUpdateAmount}
            variant="contained"
            disabled={loading}
            startIcon={loading ? <CircularProgress size={20} /> : null}
          >
            {loading ? 'Updating...' : 'Update & Confirm'}
          </Button>
        </DialogActions>
      </Dialog>
    </Card>
  );
};

export default AutoGeneratedBillsList;

