import React from 'react';
import {
  Card,
  CardContent,
  Typography,
  Box,
  Alert,
  IconButton,
  List,
  ListItem,
  ListItemText,
  Chip,
  Badge,
  Button,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField,
  CircularProgress,
} from '@mui/material';
import {
  NotificationsActive,
  Close,
  Warning,
  Info,
  CheckCircle,
  Error,
  AutoAwesome,
  Edit,
} from '@mui/icons-material';
import { BillAlert, Bill } from '../../types/bill';
import { apiService } from '../../services/api';
import { getErrorMessage } from '../../utils/validation';

interface BillAlertsProps {
  alerts: BillAlert[];
  autoGeneratedBills?: Bill[];
  onAlertRead?: () => void;
  onBillConfirmed?: () => void;
}

const BillAlerts: React.FC<BillAlertsProps> = ({ alerts, autoGeneratedBills = [], onAlertRead, onBillConfirmed }) => {
  const unreadAlerts = alerts.filter(alert => !alert.read);
  const [confirmingBillId, setConfirmingBillId] = React.useState<string | null>(null);
  const [updateDialogBill, setUpdateDialogBill] = React.useState<Bill | null>(null);
  const [updateAmount, setUpdateAmount] = React.useState(0);
  const [updateNotes, setUpdateNotes] = React.useState('');
  const [loading, setLoading] = React.useState(false);
  const [error, setError] = React.useState('');

  const getAlertIcon = (severity: string) => {
    switch (severity) {
      case 'error':
        return <Error sx={{ fontSize: 20 }} />;
      case 'warning':
        return <Warning sx={{ fontSize: 20 }} />;
      case 'success':
        return <CheckCircle sx={{ fontSize: 20 }} />;
      case 'info':
      default:
        return <Info sx={{ fontSize: 20 }} />;
    }
  };

  const getAlertTypeLabel = (type: string) => {
    switch (type) {
      case 'budget_exceeded':
        return 'Budget Exceeded';
      case 'trend_increase':
        return 'Trend Alert';
      case 'unusual_spike':
        return 'Unusual Spike';
      case 'due_reminder':
        return 'Payment Due';
      case 'overdue':
        return 'Overdue';
      case 'savings':
        return 'Savings';
      default:
        return type;
    }
  };

  const handleMarkAsRead = async (alertId: string) => {
    try {
      await apiService.markAlertAsRead(alertId);
      onAlertRead?.();
    } catch (error) {
      console.error('Failed to mark alert as read:', error);
    }
  };

  const handleQuickConfirm = async (bill: Bill) => {
    try {
      setConfirmingBillId(bill.id);
      setError('');
      await apiService.confirmBillAmount(bill.id, bill.amount);
      onBillConfirmed?.();
    } catch (err: unknown) {
      setError(getErrorMessage(err, 'Failed to confirm bill'));
    } finally {
      setConfirmingBillId(null);
    }
  };

  const handleOpenUpdateDialog = (bill: Bill) => {
    setUpdateDialogBill(bill);
    setUpdateAmount(bill.amount);
    setUpdateNotes('');
  };

  const handleUpdateAmount = async () => {
    if (!updateDialogBill) return;

    try {
      setLoading(true);
      setError('');
      
      if (updateAmount <= 0) {
        setError('Amount must be greater than 0');
        return;
      }

      await apiService.confirmBillAmount(updateDialogBill.id, updateAmount, updateNotes);
      setUpdateDialogBill(null);
      onBillConfirmed?.();
    } catch (err: unknown) {
      setError(getErrorMessage(err, 'Failed to update bill amount'));
    } finally {
      setLoading(false);
    }
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  const totalNotifications = alerts.length + autoGeneratedBills.length;

  if (totalNotifications === 0) {
    return (
      <Card>
        <CardContent sx={{ p: 2 }}>
          <Box sx={{ textAlign: 'center', py: 3 }}>
            <NotificationsActive sx={{ fontSize: 48, color: 'text.secondary', mb: 2 }} />
            <Typography variant="subtitle2" color="text.secondary">
              No Notifications
            </Typography>
            <Typography variant="caption" color="text.secondary">
              You're all caught up!
            </Typography>
          </Box>
        </CardContent>
      </Card>
    );
  }

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
    }).format(amount);
  };

  return (
    <Card>
      <CardContent sx={{ p: 2 }}>
        <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', mb: 2 }}>
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
            <Typography variant="subtitle1" fontWeight="bold">🔔 Notifications</Typography>
            {(unreadAlerts.length + autoGeneratedBills.length) > 0 && (
              <Badge badgeContent={unreadAlerts.length + autoGeneratedBills.length} color="error" />
            )}
          </Box>
        </Box>

        {error && (
          <Alert severity="error" sx={{ mb: 1, p: 1 }} onClose={() => setError('')}>
            <Typography variant="caption">{error}</Typography>
          </Alert>
        )}

        <List disablePadding>
          {/* Auto-Generated Bills First */}
          {autoGeneratedBills.map((bill) => (
            <ListItem
              key={`auto-${bill.id}`}
              sx={{
                border: 1,
                borderColor: 'primary.light',
                borderRadius: 1,
                mb: 1,
                p: 1,
                flexDirection: 'column',
                alignItems: 'flex-start',
                bgcolor: 'action.hover',
              }}
            >
              <Box sx={{ display: 'flex', alignItems: 'flex-start', gap: 1, width: '100%', mb: 1 }}>
                <AutoAwesome sx={{ fontSize: 18, color: 'primary.main', mt: 0.5 }} />
                <Box sx={{ flex: 1 }}>
                  <Typography variant="caption" fontWeight="bold" display="block">
                    {bill.billName}
                  </Typography>
                  <Typography variant="caption" color="text.secondary" display="block">
                    {bill.provider} • {formatCurrency(bill.amount)}
                  </Typography>
                  <Typography variant="caption" color="text.secondary" display="block">
                    Due: {new Date(bill.dueDate).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}
                  </Typography>
                </Box>
              </Box>
              <Box sx={{ display: 'flex', gap: 0.5, width: '100%', mt: 0.5 }}>
                <Button
                  size="small"
                  variant="contained"
                  color="success"
                  onClick={() => handleQuickConfirm(bill)}
                  disabled={confirmingBillId === bill.id}
                  fullWidth
                  sx={{ fontSize: '0.7rem', py: 0.5 }}
                >
                  ✓ Confirm
                </Button>
                <Button
                  size="small"
                  variant="outlined"
                  onClick={() => handleOpenUpdateDialog(bill)}
                  fullWidth
                  sx={{ fontSize: '0.7rem', py: 0.5 }}
                >
                  Update
                </Button>
              </Box>
            </ListItem>
          ))}

          {/* Regular Alerts */}
          {alerts.map((alert, index) => (
            <ListItem
              key={alert.id}
              sx={{
                border: 1,
                borderColor: 'divider',
                borderRadius: 1,
                mb: 1,
                p: 1,
                flexDirection: 'column',
                alignItems: 'flex-start',
                bgcolor: alert.read ? 'background.paper' : 'action.hover',
                '&:last-child': { mb: 0 },
              }}
            >
              <Box sx={{ display: 'flex', alignItems: 'flex-start', gap: 1, width: '100%', mb: 0.5 }}>
                <Box sx={{ color: `${alert.severity}.main`, mt: 0.5 }}>
                  {getAlertIcon(alert.severity)}
                </Box>
                <Box sx={{ flex: 1 }}>
                  <Typography variant="caption" fontWeight="bold" display="block">
                    {alert.title}
                  </Typography>
                  <Typography variant="caption" color="text.secondary" display="block" sx={{ mt: 0.5 }}>
                    {alert.message}
                  </Typography>
                  {alert.provider && (
                    <Typography variant="caption" color="text.secondary" display="block" sx={{ mt: 0.5 }}>
                      {alert.provider}
                    </Typography>
                  )}
                  {alert.amount && (
                    <Typography variant="caption" color="text.secondary" display="block">
                      ${alert.amount.toLocaleString()}
                    </Typography>
                  )}
                </Box>
                <IconButton
                  size="small"
                  onClick={() => handleMarkAsRead(alert.id)}
                  disabled={alert.read}
                  sx={{ p: 0.5 }}
                >
                  <Close fontSize="small" />
                </IconButton>
              </Box>
            </ListItem>
          ))}
        </List>
      </CardContent>

      {/* Update Amount Dialog */}
      <Dialog open={!!updateDialogBill} onClose={() => setUpdateDialogBill(null)} maxWidth="xs" fullWidth>
        <DialogTitle sx={{ pb: 1 }}>Update Bill Amount</DialogTitle>
        <DialogContent>
          {updateDialogBill && (
            <Box sx={{ mt: 1 }}>
              <Typography variant="caption" color="text.secondary" display="block" gutterBottom>
                {updateDialogBill.billName}
              </Typography>
              <Typography variant="caption" color="text.secondary" display="block" sx={{ mb: 2 }}>
                Estimated: {formatCurrency(updateDialogBill.amount)}
              </Typography>

              <TextField
                fullWidth
                label="Actual Amount"
                type="number"
                value={updateAmount}
                onChange={(e) => setUpdateAmount(parseFloat(e.target.value) || 0)}
                InputProps={{
                  startAdornment: '$',
                }}
                inputProps={{ min: 0, step: 0.01 }}
                size="small"
                sx={{ mb: 2 }}
              />

              <TextField
                fullWidth
                label="Notes (Optional)"
                value={updateNotes}
                onChange={(e) => setUpdateNotes(e.target.value)}
                multiline
                rows={2}
                size="small"
                placeholder="Why different from estimate?"
              />
            </Box>
          )}
        </DialogContent>
        <DialogActions sx={{ px: 3, pb: 2 }}>
          <Button onClick={() => setUpdateDialogBill(null)} size="small">
            Cancel
          </Button>
          <Button
            onClick={handleUpdateAmount}
            variant="contained"
            disabled={loading}
            size="small"
            startIcon={loading ? <CircularProgress size={16} /> : null}
          >
            {loading ? 'Updating...' : 'Update'}
          </Button>
        </DialogActions>
      </Dialog>
    </Card>
  );
};

export default BillAlerts;

